FROM golang:1.11.5 as vdcAgent
WORKDIR /opt
COPY . .
RUN CGO_ENABLED=0 go build -a --installsuffix cgo --ldflags="-w -s -X main.Build=$(git rev-parse --short HEAD)" -o request-monitor

FROM alpine:latest
COPY --from=vdcAgent /opt/request-monitor request-monitor
EXPOSE 80
EXPOSE 443
CMD [ "./request-monitor" ]
